### ISSUE TITLE
Should there be newlines at the end of every printed output?

### ISSUE THREAD

**Issue by erp12** [thelmuth/program-synthesis-benchmark-datasets#7]
Usually printed output is followed by a newline, but the printed outputs in these datasets (I only checked RSWN) only contain the string to be output.

Some GP systems may synthesize programs which contain actual calls to the host language's printing function and capture standard out during evolution for evaluation. In these cases, the GP system would have to use a version of the print function which does not add a newline to stdout (ie. `print` instead of `println`).

I think this is a small issue. Most GP system likely prefer to return a string rather than print, but I ran into it and thought it was at least worth writing down.

**Comment by thelmuth** [comment]
This is a good question. After spending some time thinking about it, I think we should leave it as-is, though maybe a note should be made somewhere.

One reason to leave it as-is is because the printed outputs for some problems would clearly need to use a printing function that doesn't always add a newline. For example, with the Grade problem, the output has to be something like "Student has a B grade.", where the B is calculated and the rest come from two different problem-specific constants. I would imagine this would be printed by 3 different calls to the print function, putting them all on one line. If the print function added a newline each time, this would require concatenating the strings before printing once, which seems more complex than necessary.

**Comment by erp12** [comment]
That seems reasonable to me. Closing!
